slack/urls.py
from django.urls import path
from slack import views
from django.contrib.auth import views as auth_views

app_name = 'slack'
urlpatterns = [
    # slack
    path('', views.index, name='index'),   # 一覧
    path('login/', auth_views.LoginView.as_view(template_name='slack/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('status/<int:user_id>/<str:status>/', views.status, name='status'),   # ステータス修正
    path('create_seat/<int:user_id>/', views.create_seat, name='create_seat'),   # 座席を発行する
    path('user_list/', views.user_list, name='user_list'),   # user一覧
    path('user/<int:pk>/', views.user_edit, name='user_edit'),  # 詳細
    path('user/del/<int:pk>/', views.user_del, name='user_del'),  # 削除
    path('comment/', views.comment_list, name='comment_list'),   # 一覧
    path('department_list/', views.department_list, name='department_list'),  # 一覧
    path('department/<int:pk>/', views.department_edit, name='department_edit'),  # 詳細
    path('department/add/', views.department_edit, name='department_add'),  # 詳細
    path('department/del/<int:pk>/', views.department_del, name='department_del'),  # 削除
    path('create_user/', views.create_slack_menber, name='create_slack_menber'),   # ユーザー作成
]

toyoapps/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('slack/', include('slack.urls')),
]

slack/models.py
from django.db import models

# Create your models here.
class Message(models.Model):
    """Message"""
    user_code = models.CharField('code', max_length=255)
    post_time =  models.CharField('postTime', max_length=255)
    message = models.TextField('message', max_length=50000, blank=True)
    slack_comment_id = models.CharField('message', max_length=255, blank=True)
    encode_time =  models.DateTimeField('postTimes', blank=True, null=True )

    def __str__(self):
        return self.message

class SlackMember(models.Model):
    """Message"""
    name = models.CharField('名前', max_length=255, null=True, blank=True)
    slack_name =  models.CharField('slack名', max_length=255)
    slack_id = models.CharField('slackId', max_length=255)
    status = models.CharField('ステータス', max_length=255, null=True, blank=True)
    update_time = models.DateTimeField('投稿時間', null=True, blank=True)
    department = models.ForeignKey('Department', verbose_name='部署',on_delete=models.SET_NULL, blank=True, null=True, related_name='department_name')
    account = models.CharField('アカウント', max_length=255, null=True, blank=True)
    flg_seat = models.CharField('座席不要フラグ', max_length=255, null=True, blank=True, default=0)

    def __str__(self):
        return self.name

class Department(models.Model):
    """部署"""
    BRANCH = (
        (10 , '本社'),
        (20 , '滋賀支店'),
        (30 , '舞鶴支店'),
    )

    name = models.CharField('部署名', max_length=255)
    branch = models.IntegerField('支店', choices=BRANCH, blank=True, null=True)

    def __str__(self):
        return self.name

class Events(models.Model):
    """Evens"""
    summary = models.TextField('summary', max_length=5000, blank=True, null=True)
    location = models.CharField('location', max_length=255, null=True, blank=True)
    startDate = models.CharField('startDate', max_length=255, null=True, blank=True)
    endDate = models.CharField('endDate', max_length=255, null=True, blank=True)
    iCalUID = models.TextField('iCalUID', blank=True, null=True, max_length=5000 )
    etag = models.CharField('etag', max_length=255, null=True, blank=True)
    googleEventId = models.CharField('etag', max_length=255, null=True, blank=True)

    def __str__(self):
        return self.summary

class Seat(models.Model):
    """Seats"""
    seat_number = models.CharField('座席番号', max_length=255, null=True, blank=True)
    user_id = models.CharField('社員Id', blank=True, null=True, max_length=255 )
    eventDate = models.DateField('eventDate', max_length=255, null=True, blank=True)

    def __str__(self):
        return self.seat_number

slack/forms.py
from django import forms

from .models import SlackMember, Department

class SlackMemberForm(forms.ModelForm):

    class Meta:
        model = SlackMember
        fields = ('name', 'status','department',)

class DepartmentForm(forms.ModelForm):

    class Meta:
        model = Department
        fields = ('name', 'branch',)

slack/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .forms import SlackMemberForm, DepartmentForm
from django.db.models import Q
from django.contrib.auth.models import User
import datetime
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from slack.get_slack_message import get_slack
from slack.create_random_number import GetNumber
from slack.get_slackuser_list import create_user
from slack.seat_json import GetSeat
from slack.models import Message, SlackMember, Department, Seat
from slack.update_status import update_status
# from .get_googleEvent import getGoogleEvent
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import(LoginView, LogoutView)


class Logout(LoginRequiredMixin, LogoutView):
    """ログアウトページ"""
    template_name = 'slack/login.html'

@login_required()
def index(request):
    """TOPメニュー"""
    return render(request,
                  'slack/index.html',  # 使用するテンプレート
                    )  # テンプレートに渡すデータ

@login_required()
def status(request, user_id, status):
    if SlackMember.objects.filter(account=user_id).exists():
        time_now = datetime.datetime.now()
        messages.add_message(request, messages.INFO, "ステータスが" + status + "に変更されました。 ( " + str(time_now) + " )")
        status = 'システム打刻　' + status
        user = SlackMember.objects.get(account=user_id)
        m = Message(user_code=user.slack_id, message=status,
                    encode_time=time_now)
        m.save()
        update_status();

    """TOPメニュー"""
    return render(request,
                  'slack/index.html',  )  # テンプレートに渡すデータ

@login_required()
def user_list(request):
    """User List"""
    users = SlackMember.objects.all()
    return render(request,
                  'slack/user_list.html',  # 使用するテンプレート
                  {'users': users}, )  # テンプレートに渡すデータ

@login_required()
def user_edit(request, pk):
    if pk:  # idがあるとき（編集の時）
        # idで検索して、結果を戻すか、404エラー
        member = get_object_or_404(SlackMember, pk=pk)
    else:  # idが無いとき（新規の時）
        # Memberを作成
        member = SlackMember()

    # POSTの時（新規であれ編集であれ登録ボタンが押されたとき）
    if request.method == 'POST':
        # フォームを生成
        form = SlackMemberForm(request.POST, instance=member)
        if form.is_valid():  # バリデーションがOKなら保存
            member = form.save(commit=False)
            member.save()
            return redirect('slack:user_list')
    else:  # GETの時（フォームを生成）
        form = SlackMemberForm(instance=member)
        slack_id = SlackMember.objects.get(pk=pk).slack_id
        messages = Message.objects.filter(user_code=slack_id).order_by("encode_time").reverse()

    # 新規・編集画面を表示
    return render(request, 'slack/member_edit.html', dict(form=form, id=id, messages=messages))

@login_required()
def department_list(request):
    """Department List"""
    departments = Department.objects.all()
    return render(request,
                  'slack/department_list.html',  # 使用するテンプレート
                  {'departments': departments}, )  # テンプレートに渡すデータ

@login_required()
def department_edit(request, pk=None):
    if pk:  # idがあるとき（編集の時）
        # idで検索して、結果を戻すか、404エラー
        member = get_object_or_404(Department, pk=pk)
    else:  # idが無いとき（新規の時）
        # Memberを作成
        member = Department()

    # POSTの時（新規であれ編集であれ登録ボタンが押されたとき）
    if request.method == 'POST':
        # フォームを生成
        form = DepartmentForm(request.POST, instance=member)
        if form.is_valid():  # バリデーションがOKなら保存
            member = form.save(commit=False)
            member.save()
            return redirect('slack:department_list')
    else:  # GETの時（フォームを生成）
        form = DepartmentForm(instance=member)
    # 新規・編集画面を表示
    return render(request, 'slack/department_edit.html', dict(form=form, id=id))

@login_required()
def comment_list(request):
    """メッセージの一覧"""
    # salckメッセージ取込
    get_slack();
    # ステータス更新
    update_status();
    # Google Event 取得
    # getGoogleEvent();

    departments = Department.objects.all()

    slacks = SlackMember.objects.all()
    keyword = request.GET.get('query')
    key = request.GET.get('key')
    print(key)
    if keyword:
        slacks = slacks.filter(
            Q(name__contains=keyword)
        )
    if key:
        slacks = slacks.filter(
            Q(department_id=key)
        )

    return render(request,
                  'slack/slack_index.html',  # 使用するテンプレート
                  {'slacks': slacks,
                   'departments': departments},)  # テンプレートに渡すデータ


def create_slack_menber(request):
    create_user();
    return HttpResponse('Create User')

@login_required()
def user_del(request, pk):
    """削除"""
    user_id=pk
    # return HttpResponse('削除')
    user = get_object_or_404(SlackMember, pk=user_id)
    user.delete()

    return redirect('slack:user_list')

@login_required()
def department_del(request, pk):
    """削除"""
    department_id=pk
    # return HttpResponse('削除')
    dp = get_object_or_404(Department, pk=department_id)
    dp.delete()

    return redirect('slack:department_list')

@login_required()
def create_seat(request ,user_id=None):
    user_id = user_id
    d = 52
    num = ''
    seat=''
    if user_id:
        num = GetNumber(d, user_id)
    if Seat.objects.filter(eventDate=now):
        seat=GetSeat(d)
    dict = {'num':num,'seat':seat}
    return render(request,
                  'slack/seat.html', dict )  # テンプレートに渡すデータ

slack/templates/slack/department_edit.html
{% extends 'slack/base.html' %}
{% block stylesheets %}
  {{ block.super }}
  <link href="/static/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet">
  <link href="/static/vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css" rel="stylesheet">
  <link href="/static/vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css" rel="stylesheet">
  <link href="/static/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css" rel="stylesheet">
  <link href="/static/vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css" rel="stylesheet">
{% endblock stylesheets %}

{% block content %}
<div class="clearfix"></div>
<div class="right_col" role="main">
    <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <h1>部署詳細</h1>
                    <hr>
                    <form method="POST" class="post-form">
                        {% csrf_token %}
                        <div class="center">
                            <table>
                                <tr>
                                    <th>部署名:<br></th>
                                    <td>{{ form.name }}</td>
                                </tr>
                                <tr>
                                </tr>
                                <tr>
                                    <th>支店:<br></th>
                                    <td>{{ form.branch }}</td>
                                </tr>
                            </table>

                        </div>
                        <hr>
                        <button type="submit" class="btn btn-primary">保存</button>
                        <a href="{% url 'slack:department_list' %}" class="btn btn-success">戻る</a>
                    </form>
                  </div>
              </div>
        <div class="clearfix"></div>
  </div>
</div>
{% endblock %}

slack/templates/slack/department_list.html
{% extends "slack/base.html" %}
{% load i18n static %}
{% block title %}部署マスタ{% endblock title %}
{% block stylesheets %}
  {{ block.super }}
  <link href="/static/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet">
  <link href="/static/vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css" rel="stylesheet">
  <link href="/static/vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css" rel="stylesheet">
  <link href="/static/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css" rel="stylesheet">
  <link href="/static/vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css" rel="stylesheet">
{% endblock stylesheets %}

{% block content %}
<div class="right_col" role="main">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="x_panel">
            <a href="{% url 'slack:department_add' %}"  class="btn btn-primary">新規作成</a>
            <div class="row">
              <div>
                <table class="table table-striped table-bordered center">
                  <thead>
                    <tr>
                      <th scope="col">部署名</th>
                      <th scope="col">支店</th>
                    　<th scope="col">詳細</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for department in departments %}
                    <tr>
                      <td>{{ department.name }}</td>
                      <td>{{ department.get_branch_display }}</td>
                        <td>
                          <a href="{% url 'slack:department_edit' pk=department.id %}" class="btn btn-success">詳細</a>
                          <a href="{% url 'slack:department_del' pk=department.id %}" class="btn btn-danger">削除</a>
                        </td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
                </div>
            </div>
          </div>
        </div>
    </div>
</div>
{% endblock content %}

slack/templates/slack/footer.html
<div class="clearfix"></div>
<div class="pull-right">
  <a href="https://toyo-group.co.jp/">Copyright 2020 toyo-group.co.jp</a>
</div>
<div class="clearfix"></div>

slack/templates/slack/index.html
{% extends "slack/base.html" %}
{% load i18n static %}
{% block title %}勤務状況管理{% endblock title %}

{% block content %}
<div class="right_col" role="main">
    <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div>
                    <h1 class="mt-4 border-bottom"> ステータス変更 </h1>
                      {% if messages %}
                      <ul>
                        {% for message in messages %}
                        <li class="caution">{{ message }}</li>
                        {% endfor %}
                      </ul>
                      {% endif %}
                      <div class="clearfix"></div>
                          <h1 id="time"></h1>
                            <script>
                            time();
                            function time(){
                                var now = new Date();
                                document.getElementById("time").innerHTML = now.toLocaleString();
                            }
                            setInterval('time()',1000);
                            </script>
                        <div class="clearfix"></div>
                        <table class="col-md-12 col-sm-12 col-xs-12">
                            <tr>
                                <td><a  href="{% url 'slack:status' user_id=user.id status='出勤' %}"><button class="btn-success box">出勤</button></a></td>
                                <td><a  href="{% url 'slack:status' user_id=user.id status='退勤' %}"><button class="btn-success box">退勤</button></a></td>
                            </tr>
                            <tr>
                                <td><a  href="{% url 'slack:status' user_id=user.id status='リモート出勤' %}"><button class="btn-success box">リモート出勤</button></a></td>
                                <td><a  href="{% url 'slack:status' user_id=user.id status='リモート退勤' %}"><button class="btn-success box">リモート退勤</button></a></td>
                            </tr>
                            <tr>
                                <td><a  href="{% url 'slack:status' user_id=user.id status='外出' %}"><button class="btn-success box">外出</button></a></td>
                                <td><a  href="{% url 'slack:status' user_id=user.id status='社内' %}"><button class="btn-success box">社内</button></a></td>
                            </tr>
                            <tr>
                                <td>
                                    <a href="{% url 'slack:create_seat' user_id=user.id %}" ><button class="btn-primary box">座席作成</button></a>
                                </td>
                                <td></td>
                            </tr>
                          </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    <div class="clearfix"></div>
</div>
{% endblock content %}

slack/templates/slack/side_bar.html
<div class="left_col scroll-view">
  <div class="navbar nav_title" style="border: 0;">
<!--    <a href="#" class="site_title">-->
      <img src="/static/slack/img/smile_白.png" alt="..." width="25%" height="80%">

      <br>
      <span>株式会社 東洋</span>
<!--    </a>-->
  </div>

  <div class="clearfix"></div>

  <!-- menu profile quick info -->
  <div class="profile clearfix">
<!--    <div class="profile_pic">-->
<!--      <img src="/static/images/smileinit.png" alt="..." class="img-circle profile_img">-->
<!--    </div>-->
    <div class="profile_info">
      <span>Welcome,</span>
      <h2>{{ user.first_name }} {{ user.last_name }}</h2>
    </div>
  </div>
  <!-- /menu profile quick info -->

  <br />

  <!-- sidebar menu -->
  <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
    <div class="menu_section">
      <h3>General</h3>
      <ul class="nav side-menu">
          <li>
              <a href="{% url 'slack:index' %}">
              <i class="fa fa-home"></i> HOME</a>
          </li>

          <li><a href="{% url 'slack:comment_list' %}"><i class="fa fa-edit"></i> 勤務状況
          </a></li>

            <li><a href="{% url 'slack:user_list' %}"><i class="fa fa-edit"></i> 社員マスタ
            </a>
            <li><a href="{% url 'slack:department_list' %}"><i class="fa fa-edit"></i> 部署マスタ
            </a>
        </li>
<!--        <li><a href="#"><i class="fa fa-edit"></i> 座席表-->
<!--        </a>-->
<!--        </li>-->
      </ul>
    </div>
    </div>
  </div>
  <!-- /sidebar menu -->

  <!-- /menu footer buttons -->
</div>

slack/templates/slack/slack_index.html
{% extends "slack/base.html" %}
{% load i18n static %}
{% block title %}勤務状況管理{% endblock title %}
{% block stylesheets %}
  {{ block.super }}
  <link href="/static/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet">
  <link href="/static/vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css" rel="stylesheet">
  <link href="/static/vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css" rel="stylesheet">
  <link href="/static/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css" rel="stylesheet">
  <link href="/static/vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css" rel="stylesheet">
{% endblock stylesheets %}

{% block content %}
<div class="right_col" role="main">
    <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="boxContainer">
                      <form action="" method="get">
                        <a>検索条件 :</a>
                        <input name="query" value="{{ request.GET.query }}" type="text" placeholder="名前検索">
                        <select name="key" value="{{ request.GET.query }}" type="text" placeholder="部署">
                            <option value="">部署名</option>
                          {% for d in departments %}
                            <option value={{ d.id }}>{{ d.name }}</option>
                          {% endfor %}
                        </select>
                        </input>
                        <button type="submit"  class="btn btn-primary">検索</button>
                    </form>
                  </div>
                    <hr>
                  <div>
                    <table class="table table-striped table-bordered center">
                      <thead>
                        <tr>
                          <th scope="col">名前</th>
                          <th scope="col">部署</th>
                          <th scope="col">ステータス</th>
                          <th scope="col">投稿時間</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for slack in slacks %}
                        <tr>
                          <td><a href="{% url 'slack:user_edit' pk=slack.id %}">{{ slack.name }}</a></td>
                          <td>{{ slack.department }}</td>
                          <td>{{ slack.status }}</td>
                          <td>{{ slack.update_time }}</td>
                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                    </div>
                </div>
            </div>
        </div>
</div>
</div>
{% endblock content %}

slack/templates/slack/status_list.html
{% extends "slack/base.html" %}
{% load i18n static %}
{% block title %}勤務状況管理{% endblock title %}

{% block content %}
<div class="row">
  <div>
    <h1 class="mt-4 border-bottom"> 勤務状況管理 </h1>
    <table class="table table-striped table-bordered center">
        <tr>
            <td><a href="{% url 'slack:comment_list' %}">勤務状況</a></td>
        </tr>
        <tr>
            <td><a href="{% url 'slack:user_list' %}">社員マスタ</a></td>
        </tr>
        <tr>
            <td><a href="{% url 'slack:department_list' %}">部署マスタ</a></td>
        </tr>
      </tbody>
    </table>
    </div>
</div>
{% endblock content %}

slack/templates/slack/top_navigation.html
<div class="nav_menu">
  <nav>
    <div class="nav toggle">
      <a id="menu_toggle"><i class="fa fa-bars"></i></a>
    </div>

    <ul class="nav navbar-nav navbar-right">
      <li class="">
        <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
          <!-- <img src="/static/images/img.jpg" alt=""> -->
          {{ user.first_name }} {{ user.last_name }}
          <span class=" fa fa-angle-down"></span>
        </a>
        <ul class="dropdown-menu dropdown-usermenu pull-right">
          <li><a href="javascript:;"> Profile</a></li>
          <li>
            <a href="javascript:;">
              <span class="badge bg-red pull-right">50%</span>
              <span>Settings</span>
            </a>
          </li>
          <li><a href="javascript:;">Help</a></li>
          <li><a href="{% url 'slack:logout' %}"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
        </ul>
      </li>

<!--      <li role="presentation" class="dropdown">-->
<!--        <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">-->
<!--          <i class="fa fa-envelope-o"></i>-->
<!--          <span class="badge bg-green">6</span>-->
<!--        </a>-->
<!--        <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">-->
<!--          <li>-->
<!--            <a>-->
<!--              <span>-->
<!--                <span>John Doe</span>-->
<!--                <span class="time">3 mins ago</span>-->
<!--              </span>-->
<!--              <span class="message">-->
<!--                Film festivals used to be do-or-die moments for movie makers. They were where...-->
<!--              </span>-->
<!--            </a>-->
<!--          </li>-->
<!--          <li>-->
<!--            <a>-->
<!--              <span>-->
<!--                <span>John Doe</span>-->
<!--                <span class="time">3 mins ago</span>-->
<!--              </span>-->
<!--              <span class="message">-->
<!--                Film festivals used to be do-or-die moments for movie makers. They were where...-->
<!--              </span>-->
<!--            </a>-->
<!--          </li>-->
<!--          <li>-->
<!--            <a>-->
<!--              <span>-->
<!--                <span>John Doe</span>-->
<!--                <span class="time">3 mins ago</span>-->
<!--              </span>-->
<!--              <span class="message">-->
<!--                Film festivals used to be do-or-die moments for movie makers. They were where...-->
<!--              </span>-->
<!--            </a>-->
<!--          </li>-->
<!--          <li>-->
<!--            <a>-->
<!--              <span>-->
<!--                <span>John Doe</span>-->
<!--                <span class="time">3 mins ago</span>-->
<!--              </span>-->
<!--              <span class="message">-->
<!--                Film festivals used to be do-or-die moments for movie makers. They were where...-->
<!--              </span>-->
<!--            </a>-->
<!--          </li>-->
<!--          <li>-->
<!--            <div class="text-center">-->
<!--              <a>-->
<!--                <strong>See All Alerts</strong>-->
<!--                <i class="fa fa-angle-right"></i>-->
<!--              </a>-->
<!--            </div>-->
<!--          </li>-->
<!--        </ul>-->
<!--      </li>-->
    </ul>
  </nav>
</div>

slack/templates/slack/user_list.html
{% extends "slack/base.html" %}
{% load i18n static %}
{% block title %}社員マスタ{% endblock title %}
{% block stylesheets %}
  {{ block.super }}
  <link href="/static/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet">
  <link href="/static/vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css" rel="stylesheet">
  <link href="/static/vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css" rel="stylesheet">
  <link href="/static/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css" rel="stylesheet">
  <link href="/static/vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css" rel="stylesheet">
{% endblock stylesheets %}

{% block content %}
<div class="right_col" role="main">
    <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div>
                    <table class="table table-striped table-bordered center">
                      <thead>
                        <tr>
                          <th scope="col">名前</th>
                          <th scope="col">部署</th>
                        　<th scope="col">詳細</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for user in users %}
                        <tr>
                          <td>{{ user.name }}</td>
                          <td>{{ user.department }}</td>
                            <td>
                                <a href="{% url 'slack:user_edit' pk=user.id %}" class="btn btn-success">詳細</a>
                                <a href="{% url 'slack:user_del' pk=user.id %}" class="btn btn-danger">削除</a>
                            </td>
                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                    </div>
                </div>
            </div>
        </div>
</div>
</div>
{% endblock content %}